### PR TITLE
fix: add dynamic TerminalOpen for both vim and nvim

### PR DESCRIPTION
**Pull request by nusendra**
image

Add dynamic TermOpen / TerminalOpen for both vim / nvim

### CODE REVIEW

**Review by znculee — APPROVED** [review]
LGTM! Thanks for the fix! I've tested it works on both vim and nvim.

**Review by PabloScolpino — APPROVED** [review]
Thanks for stepping up. Sorry for the 📻 silence.

**Comment by moniquelive** [comment]
@bronson could you merge this? it's soooo annoying 🙏🏻

**Comment by bronson** [comment]
Yikes, I did the thing I tell everyone not to do ... perform a last few easy merges right before going on vacation. I'm sorry for the delay.

It would be good to reduce the bus factor here ... If anyone who's interacted with this plugin in the past would want to also be a maintainer, hit me up. It doesn't take much time and an extra set of eyes would be good.

Thank you everyone for the productive patches and discussion

**Pull request merged**
